apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abalpha-jupyterhub
  namespace: fiquantit-prod
  labels:
    app: abalpha-jupyterhub
    namespace: fiquantit-prod
    labels:
      app: abalpha-jupyterhub
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: 10000m
spec:
  tls:
  - hosts:
    - abalpha-jupyterhub.aks-cortex-prod-003.acml.com
  rules:
    - host: abalpha-jupyterhub.aks-cortex-prod-003.acml.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-public
                port:
                  name: http
